category_size = 3
language = 'en-us'

[genshin]
file.json.path = "genshin.json"
file.json.url = "https://example.org/genshin.json"
file.atom.path = "genshin.xml"
file.atom.url = "https://example.org/genshin.xml"
title = "Genshin Impact News"
icon = "https://img-os-static.hoyolab.com/favicon.ico"
