name: Test and Deploy
on: [push]
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: flake8 --ignore E501 *.py
      - name: Test with pytest
        run: pytest
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          SOURCE: "hoyolab.py"
          TARGET: "/srv/www/scripts/"
          ARGS: "-auvz"
