name: Release

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASENOTES.md

  build:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m pip install "setuptools_scm[toml]"
      - name: Show version
        run: python -m setuptools_scm
      - name: Build Distribution
        run: python -m build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist/*
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: PyPI
      url: https://pypi.org/project/hoyolab-rss-feeds
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: dist
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
